
spring:
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.168.70:3307/homecloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: cfy39177
    hikari:
      #最大连接时间
      max-lifetime: 3600000
      #最大连接数
      maximum-pool-size: 20
      #最小空闲数
      minimum-idle: 10
      #空闲超时时间
      idle-timeout: 600000
      #连接超时时间
      connection-timeout: 30000
      auto-commit: true

  messages:
    basename: i18n/messages
  # redis 配置
  redis:
    # 地址
    host: 43.139.168.70
    # 端口，默认为6379
    # 数据库索引
    port: 6379
    database: 0
    # 密码
    password: cfy39177
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#  main:
#    allow-bean-definition-overriding: true

#Mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰转换
    map-underscore-to-camel-case: true

token:
  #token 请求头Key
  header: Authorization
  #token有效时间30分钟
  expireTime: 30
  #token密钥
  secret: $jest$sdhnjsd?hdbhsdscvd$

mqtt:
  #服务器地址
  broker: tcp://43.139.168.70:1883
  #随机客户端ID
  client_id: ${random.long}
  in_client_id: hc #${random.long} 使用随机客户端id无法接收历史消息
  out_client_id: ${random.long}
  #默认订阅主题
  default_topic: bing
  timeout: 60
  keepalive: 60
  #是否清理会话
  clearSession: false

minio:
  url: http://43.139.168.70
  port: 9000
  access_key: qNjka6wpP1FEeltMQX77
  secret_key: FqMXKwDBrNqY2AxuYN06S8HRFE65DKazRQZRFtMV




